version: "3.8"
services:
  backend:
    image: "tapiwazireva/springboot-react-fullstack:5.4.2021.20.4.58"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev