version: "3.8"
services:
  backend:
    image: "tapiwazireva/springboot-react-fullstack:1.4.2021.23.6.44"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev